# Global settings - most REQUIRED

time_framework = [2020, 2025, 2030, 2035, 2040, 2045, 2050]
regions = ["R1"]
interpolation_mode = 'linear'
log_level = 'info'
excluded_commodities = ["wind"]
# Convergence parameters
equilibrium_variable = 'demand'
maximum_iterations = 100
tolerance = 0.1
tolerance_unmet_demand = -0.1

[[outputs]]
quantity = "capacity"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/MCA{Quantity}.csv"

[[outputs]]
quantity = "prices"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/MCA{Quantity}.csv"

[carbon_budget_control]
budget = []

[global_input_files]
projections = '{path}/Projections.csv'
global_commodities = '{path}/GlobalCommodities.csv'

[sectors.residential]
type = 'default'
priority = 1
dispatch_production = 'share'
technodata = '{path}/residential/Technodata.csv'
commodities_in = '{path}/residential/CommIn.csv'
commodities_out = '{path}/residential/CommOut.csv'

[sectors.residential.subsectors.all]
agents = '{path}/Agents.csv'
existing_capacity = '{path}/residential/ExistingCapacity.csv'
lpsolver = "scipy"  # Optional, defaults to "scipy"
constraints = [
    # Optional, defaults to the constraints below
    "max_production",
    "max_capacity_expansion",
    "demand",
    "search_space",
    "minimum_service",
    "demand_limiting_capacity"
]
demand_share = "standard_demand"  # Optional, default to standard_demand

[sectors.power]
type = 'default'
priority = 2
dispatch_production = 'share'
technodata = '{path}/power/Technodata.csv'
technodata_timeslices = '{path}/power/TechnodataTimeslices.csv'
commodities_in = '{path}/power/CommIn.csv'
commodities_out = '{path}/power/CommOut.csv'

[sectors.power.subsectors.all]
agents = '{path}/Agents.csv'
existing_capacity = '{path}/power/ExistingCapacity.csv'
lpsolver = "scipy"
demand_share = "standard_demand"

[[sectors.power.outputs]]
quantity = "supply"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/{Sector}_{Quantity}.csv"

[sectors.gas]
type = 'default'
priority = 3
dispatch_production = 'share'
technodata = '{path}/gas/Technodata.csv'
commodities_in = '{path}/gas/CommIn.csv'
commodities_out = '{path}/gas/CommOut.csv'

[sectors.gas.subsectors.all]
agents = '{path}/Agents.csv'
existing_capacity = '{path}/gas/ExistingCapacity.csv'
lpsolver = "scipy"
demand_share = "standard_demand"

[sectors.residential_presets]
type = 'presets'
priority = 0
consumption_path = "{path}/residential_presets/*Consumption.csv"

[timeslices]
level_names = ["month", "day", "hour"]

[timeslices.all-year.all-week]
night = 1460
morning = 1460
afternoon = 1460
early-peak = 1460
late-peak = 1460
evening = 1460
