time_framework = [2020, 2025, 2030, 2035, 2040, 2045, 2050]
foresight = 5
regions = ["R1", "R2"]
interest_rate = 0.1
interpolation_mode = "Active"
log_level = "info"
excluded_commodities = ["wind", "solar"]
equilibrium_variable = "demand"
maximum_iterations = 100
tolerance = 0.1
tolerance_unmet_demand = -0.1

[[outputs]]
quantity = "prices"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/MCA{Quantity}.csv"

[[outputs]]
quantity = "capacity"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/MCA{Quantity}.csv"
index = false
keep_columns = ["technology", "dst_region", "region", "agent", "sector", "type", "year", "capacity"]

[carbon_budget_control]
budget = []
method = "fitting"

[global_input_files]
projections = "{path}/input/Projections.csv"
global_commodities = "{path}/input/GlobalCommodities.csv"

[timeslices]
level_names = ["month", "day", "hour"]

[timeslices.all-year.all-week]
night = 1460
morning = 1460
afternoon = 1460
early-peak = 1460
late-peak = 1460
evening = 1460

[sectors.residential]
type = "default"
priority = 1
dispatch_production = "share"
technodata = "{path}/technodata/residential/Technodata.csv"
commodities_in = "{path}/technodata/residential/CommIn.csv"
commodities_out = "{path}/technodata/residential/CommOut.csv"

[[sectors.residential.outputs]]
filename = "{cwd}/{default_output_dir}/{Sector}/{Quantity}/{year}{suffix}"
quantity = "capacity"
sink = "csv"
overwrite = true
index = false

[[sectors.residential.outputs]]
filename = "{cwd}/{default_output_dir}/{Sector}/{Quantity}/{year}{suffix}"
sink = "csv"
overwrite = true

[sectors.residential.outputs.quantity]
name = "supply"
sum_over = "timeslice"
drop = ["comm_usage", "units_prices"]

[[sectors.residential.interactions]]
net = "new_to_retro"
interaction = "transfer"

[sectors.residential.subsectors.retro_and_new]
agents = "{path}/technodata/Agents.csv"
existing_capacity = "{path}/technodata/residential/ExistingCapacity.csv"
lpsolver = "scipy"
constraints = ["max_production", "max_capacity_expansion", "demand", "search_space"]
demand_share = "new_and_retro"
forecast = 5

[sectors.power]
type = "default"
priority = 2
dispatch_production = "share"
technodata = "{path}/technodata/power/Technodata.csv"
commodities_in = "{path}/technodata/power/CommIn.csv"
commodities_out = "{path}/technodata/power/CommOut.csv"

[[sectors.power.outputs]]
filename = "{cwd}/{default_output_dir}/{Sector}/{Quantity}/{year}{suffix}"
quantity = "capacity"
sink = "csv"
overwrite = true
index = false

[[sectors.power.interactions]]
net = "new_to_retro"
interaction = "transfer"

[sectors.power.subsectors.retro_and_new]
agents = "{path}/technodata/Agents.csv"
existing_capacity = "{path}/technodata/power/ExistingCapacity.csv"
lpsolver = "scipy"

[sectors.gas]
type = "default"
priority = 3
dispatch_production = "share"
technodata = "{path}/technodata/gas/Technodata.csv"
commodities_in = "{path}/technodata/gas/CommIn.csv"
commodities_out = "{path}/technodata/gas/CommOut.csv"

[[sectors.gas.outputs]]
filename = "{cwd}/{default_output_dir}/{Sector}/{Quantity}/{year}{suffix}"
quantity = "capacity"
sink = "csv"
overwrite = true
index = false

[[sectors.gas.interactions]]
net = "new_to_retro"
interaction = "transfer"

[sectors.gas.subsectors.retro_and_new]
agents = "{path}/technodata/Agents.csv"
existing_capacity = "{path}/technodata/gas/ExistingCapacity.csv"
lpsolver = "scipy"

[sectors.residential_presets]
type = "presets"
priority = 0
consumption_path = "{path}/technodata/preset/*Consumption.csv"
