name: Legacy tests

on:
  push:
    branches:
    - development
    - master

  pull_request:
    branches:
    - development
    - master

jobs:
  build:
    runs-on: ${{ matrix.imageName }}
    strategy:
      matrix:
        imageName: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.8]
    steps:
    - name: Checkout MUSE
      uses: actions/checkout@v2

    - name: Checkout Legacy MUSE
      uses: actions/checkout@v2
      with:
        repository: SGIModel/StarMuse
        ref: archive/legacy
        path: LegacyMuse

    - name: Checkout MUSE Data
      uses: actions/checkout@v2
      with:
        repository: SGIModel/SGIModelData
        ref: master
        path: SGIModelData
        token: ${{ secrets.MUSE }}

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -U setuptools wheel xlrd==1.2.0

    - name: Install MUSE Data
      run: pip install ./SGIModelData

    - name: Install Legacy MUSE
      run: pip install ./LegacyMuse

    - name: Install MUSE
      run:  pip install -e .[dev,excel]

    - name: Run tests in Linux
      if: (runner.os == 'Linux')
      run: |
        pip install pytest-cov
        pytest -m "legacy" --junitxml=junit/pytest.xml \
            --cov=muse \
            --cov-branch \
            --cov-report=xml:coverage/coverage.xml

    - name: Run tests in Windows and MacOS
      if: (runner.os != 'Linux')
      run: |
        pytest --junitxml=junit/pytest.xml
