name: open-source regression-tests

on:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches: [master, development]

jobs:
  regression-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Test with pytest
      run: |
        pytest -m "regression"
